AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A simple backend (read/write to DynamoDB) with a RESTful API endpoint using
  Amazon API Gateway.
Resources:
  testAPI:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: testAPI/
      Description: >-
        A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 512
      Timeout: 10
      Role: 'arn:aws:iam::031968646416:role/service-role/adminAPI'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /testAPI
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /
            Method: ANY
      Environment:
        Variables:
          executelocal: false
      Tags:
        'lambda-console:blueprint': microservice-http-endpoint-python
